baseurl = "https://seng.netlify.app/"
languageCode = "en-us"
title = "Social Ecological Networks Group"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight=1
[[menu.main]]
    name = "People"
    url = "/people/"
    weight=2
[[menu.main]]
    name = "Archives"
    url = "/post/"
    weight=3
    
[[menu.main]]
    name = "Canon"
    url = "/canon/"
    weight=4

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight=5
    
[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "SENG_Circle_NoOutline.png"
    width = 50
    height = 50
    alt = "Logo"

