---
title: Spring 2023 Schedule
author: SENG
date: '2023-01-06'
slug: spring-2023-schedule
categories:
  - general
tags:
  - informational
---

## Meeting Information 

Welcome back network folx! 

This semester, we will have 7 meetings. Something new we are doing this semester are *Informal Workshops*. In these workshops, we will meet in person to discuss our projects and work together to solve some of our analysis challenges. You can think of these workshops as a time to drop-in, say hello, and work collectively on our individual projects. We will keep a zoom room open as well so that our non-Columbus members can stop in and ask questions. 

- **Time**: 3PM Eastern Standard Time
- **Dates**: 1/27, 2/10, 2/24, 3/10, 3/24, 4/14, 4/28
- **Zoom**: [Join meeting](https://osu.zoom.us/j/7886600344?pwd=ZmYweUt6MFBvRlYvdHhjeU9CZnhlZz09)
- **Passcode**: 002244
- **Location**: Pomerene Hall 350

Date                                                 Topic              Location
------------------------  --------------------------------  --------------------
2023-01-27                              Geographic Networks                 Zoom
2022-02-10                              Informal Workshop I        Pomerene Hall
2022-02-24                      Advanced Data Visualization                 Zoom
2022-03-10                             Application of ERGMs        Pomerene Hall
2022-03-24                                 Bayesian Methods                 Zoom
2022-04-14                             Informal Workshop II        Pomerene Hall
2022-04-28                                              TBD                 Zoom  

Our four topical meetings will be an Introduction to Geographic Networks (led by Harrison Fried), advanced data visualization techniques (led by Shane Scaggs), the application of ERGM in Public Administration: Take Interstate Benchmarking Networks as an Example (led by Shuai Cao), and Bayesian Methods (led by Shane Scaggs). We have one date still open to let us know if there is anything you want to share or cover in that meeting. 