---
title: 'A Primer on Network Graph Notation '
author: 'Shane A. Scaggs'
date: '2022-04-15'
slug: a-primer-on-network-graph-notation
categories:
  - theory
tags:
  - notation
  - nodes
  - edges
  - graphs
draft: yes
---

You can always tell when an article about networks is about to get formal. It usually happens just after the background, when the author writes, "Let $N = \{1,2,...n\}$, where $i$ is..." What does all this notation mean and why do we needed? In this post, I'll tell you. 

# Notation 

Notation is not that different from language. In fact, some talk about mathematical or scientific notation as a kind of language. The languages we speak everyday are dynamic; the meaning of words changes and is repurposed to fit different situations. Like everyday language, notation has a grammar and a syntax. The main difference is thatthe syntactic and semantic rules that govern how the notation is used is strict and hardly, if ever, changes to fit specific situations. 

The purpose of notation is similar to language; to give users a collective basin of meaning which can be used to communication effectively. Because of the dynamism of language, it is not uncommon for two people to miscommunicate during a conversation, requiring them to navigate their way back to a collective understanding. The strict rules of notation exist to help us to avoid this detour. This enables scientists to communicate a great deal of complex information in a compact way. If each symbol or sentence in notation required a shared justification of meaning, it would be impossible to write proofs and equations the way we do today. 


A network graph is represented by $g$, and a subset of $g$ -- a connected component or clique -- is represented by $g'$. 